import {useEffect,useMemo,useRef,useState} from 'react';
import {Quaternion,Vector2,Vector3} from 'three';
import {castingAsset} from './castingAsset';
import {CastRenderer,type CastSettings,type CastPose} from './CastRenderer';
import {HandTracker} from './HandTracker';
import {CastGesture,estimatePalm,type Hand,type PalmPose} from './handPose';
export type CastAsset={text:string;name:string};
export type CastSession={settings?:CastSettings;file?:File;kind?:'photo'|'video';time?:number;videoTime?:number;mirror?:boolean;anchor?:{x:number;y:number;depth:number};tracking?:boolean;handChoice?:string;debug?:boolean;tab?:string};
const defaults:CastSettings={size:2.5,spacing:.5,offset:.5,fov:50,duration:1.2,flip:false,pitch:-20,yaw:25,roll:0,reverse:false,solo:-1,glow:0,opacity:1,order:[]};
export function CastPage({asset,onAsset,onCurrent,onImported,session}:{asset:CastAsset|null;onAsset:(a:CastAsset)=>void;onCurrent:()=>void;onImported:()=>void;session:CastSession}){
 const [settings,setSettings]=useState({...defaults,...session.settings}),[tab,setTab]=useState(session.tab||'input'),[error,setError]=useState('');
 const [file,setFile]=useState<File|null>(session.file||null),[kind,setKind]=useState<'photo'|'video'|'camera'>(session.kind||'photo'),[url,setUrl]=useState('');
 const [tracking,setTracking]=useState(session.tracking??!!session.file),[status,setStatus]=useState('手动模式 · 点击画面放置法阵'),[handChoice,setHandChoice]=useState(session.handChoice||'auto'),[cameraActive,setCameraActive]=useState(false),[debug,setDebug]=useState(session.debug||false);
 const stream=useRef<MediaStream|null>(null),cameraTicket=useRef(0),tracker=useRef<HandTracker|null>(null),gesture=useRef(new CastGesture());
 const observation=useRef<{pose:PalmPose|null;seen:number;hands:Hand[]}>({pose:null,seen:0,hands:[]}),selectedHand=useRef<{label:string;x:number;y:number}|null>(null),visibility=useRef(1);
 const [dimensions,setDimensions]=useState({w:1280,h:720}),[mirror,setMirror]=useState(session.mirror||false),[playing,setPlaying]=useState(true),[time,setTime]=useState(session.time||0);
 const [anchor,setAnchor]=useState(session.anchor||{x:.5,y:.55,depth:8}),[exporting,setExporting]=useState(false);
 const exportLock=useRef(false),lastVideoFrame=useRef(-1),seekReveal=useRef(false);
 const host=useRef<HTMLDivElement>(null),video=useRef<HTMLVideoElement>(null),photo=useRef<HTMLImageElement>(null),engine=useRef<CastRenderer|null>(null);
 const elapsed=useRef(0),clock=useRef(time),state=useRef({settings,playing,kind,anchor,tracking,handChoice,dimensions});state.current={settings,playing,kind,anchor,tracking,handChoice,dimensions};
 const lastPose=useRef<CastPose>({position:new Vector3(0,0,-8),rotation:new Quaternion()});
 const source=useMemo(()=>{try{return asset?{value:castingAsset(asset.text),error:''}:{value:null,error:''};}catch(e){return {value:null,error:String(e)};}},[asset]);
 useEffect(()=>{const count=source.value?.layers.length||0;setSettings(s=>({...s,solo:-1,order:s.order.length===count&&new Set(s.order).size===count&&s.order.every(i=>i>=0&&i<count)?s.order:Array.from({length:count},(_,i)=>i)}));},[source]);
 useEffect(()=>{Object.assign(session,{settings,file:file||undefined,kind:kind==='camera'?'photo':kind,time,videoTime:kind==='video'?video.current?.currentTime:session.videoTime,mirror,anchor,tracking:kind==='camera'?false:tracking,handChoice,debug,tab});},[session,settings,file,kind,time,mirror,anchor,tracking,handChoice,debug,tab]);
 useEffect(()=>{if(!file){setUrl('');return;}const next=URL.createObjectURL(file);setUrl(next);return()=>URL.revokeObjectURL(next);},[file]);
 useEffect(()=>{if(!source.value||!host.current)return;let renderer:CastRenderer;try{renderer=new CastRenderer(host.current,source.value);}catch(e){setError(`三维画布无法启动：${e}`);return;}
  engine.current=renderer;let stopped=false,frame=0,last=performance.now(),updated=-1,ui=0,busy=false,textureReady=false;elapsed.current=0;gesture.current.elapsed=0;
  const loop=(now:number)=>{if(stopped)return;const dt=Math.min(.1,(now-last)/1000);last=now;if(exportLock.current){frame=requestAnimationFrame(loop);return;}const s=state.current;
   if(s.kind==='video'&&video.current)clock.current=video.current.currentTime;else if(s.playing&&textureReady)clock.current+=dt;
   const advancing=textureReady&&(s.kind==='video'?!video.current?.paused:s.playing);
   if(advancing)elapsed.current+=dt;
   const t=source.value!.duration?clock.current%source.value!.duration:0;
   if(!busy&&Math.abs(t-updated)>(advancing?.065:1e-6)){busy=true;updated=t;const resolution=Math.min(1024,Math.max(256,Math.floor(Math.sqrt(8_000_000/source.value!.layers.length))));void renderer.textures(t,resolution).then(()=>{if(!stopped&&!textureReady){elapsed.current=0;gesture.current.elapsed=0;textureReady=true;}}).catch(e=>{if(!stopped)setError(`法阵纹理更新失败：${e}`);}).finally(()=>busy=false);}
   const height=2*s.anchor.depth*Math.tan(s.settings.fov*Math.PI/360),aspect=renderer.camera.aspect;
   if(s.tracking){const observed=observation.current,valid=!!observed.pose&&(s.kind==='photo'||(s.kind==='video'&&video.current?.paused)||now-observed.seen<300);
    const previousElapsed=gesture.current.elapsed;gesture.current.tick(valid?observed.pose!.open:null,now/1000,dt);if(!advancing)gesture.current.elapsed=previousElapsed;
    if(valid)lastPose.current=observed.pose!;visibility.current=gesture.current.visible;elapsed.current=gesture.current.elapsed;
   }else{lastPose.current={position:new Vector3((s.anchor.x-.5)*height*aspect,(.5-s.anchor.y)*height,-s.anchor.depth),rotation:new Quaternion()};visibility.current=1;}
   renderer.draw(s.settings,lastPose.current,elapsed.current,visibility.current,dt);
   if(now-ui>150){setTime(t);ui=now;}frame=requestAnimationFrame(loop);
  };frame=requestAnimationFrame(loop);return()=>{stopped=true;cancelAnimationFrame(frame);renderer.dispose();engine.current=null;};
 },[source]);
 useEffect(()=>{if(!tracking||(!url&&!cameraActive))return;observation.current={pose:null,seen:0,hands:[]};gesture.current.reset();selectedHand.current=null;
  const detector=new HandTracker(hands=>{const s=state.current;let candidates=hands.filter(h=>s.handChoice==='auto'||h.label===s.handChoice);
   if(selectedHand.current&&s.handChoice==='auto'){const same=candidates.filter(h=>h.label===selectedHand.current!.label);if(same.length)candidates=same;}
   const area=(h:Hand)=>{const xs=h.landmarks.map(p=>p.x),ys=h.landmarks.map(p=>p.y);return (Math.max(...xs)-Math.min(...xs))*(Math.max(...ys)-Math.min(...ys));};
   candidates.sort((a,b)=>{const p=selectedHand.current;if(p){const dist=(h:Hand)=>Math.hypot(h.landmarks[9].x-p.x,h.landmarks[9].y-p.y);return dist(a)-dist(b);}return area(b)-area(a);});
   const hand=candidates[0],pose=hand?estimatePalm(hand,s.dimensions.w/s.dimensions.h,s.settings.fov):null;
   if(seekReveal.current&&s.kind==='video'&&video.current?.paused&&pose){
    // Seeking requests a still frame: reconstruct an unfolded preview at that media time.
    gesture.current.active=pose.open>.78;gesture.current.visible=Number(gesture.current.active);gesture.current.elapsed=Math.min(s.settings.duration,video.current.currentTime);seekReveal.current=false;
   }
   if(hand&&pose)selectedHand.current={label:hand.label,x:hand.landmarks[9].x,y:hand.landmarks[9].y};
   observation.current={pose,seen:performance.now(),hands};setStatus(!hand?'没有检测到选定手掌':!pose?'掌面角度不稳定，请稍微转向镜头':`${hand.label==='Left'?'左手':'右手'} · ${pose.open>.78?'张掌施法':'等待张开手掌'}`);
  },setStatus);tracker.current=detector;lastVideoFrame.current=-1;let photoDone=false;
  const timer=setInterval(()=>{const s=state.current;if(s.kind==='photo'){if(!photoDone&&photo.current?.complete&&photo.current.naturalWidth)void detector.detect(photo.current,performance.now(),true).then(sent=>{if(sent)photoDone=true;});}
   else if(video.current&&video.current.readyState>=2){const t=video.current.currentTime;if(t!==lastVideoFrame.current)void detector.detect(video.current,t*1000).then(sent=>{if(sent)lastVideoFrame.current=t;});}
  },70);
  return()=>{clearInterval(timer);detector.dispose();tracker.current=null;};
 },[tracking,url,cameraActive,kind,handChoice,settings.fov]);
 useEffect(()=>{if(cameraActive&&video.current&&stream.current){video.current.srcObject=stream.current;void video.current.play().catch(e=>setError(String(e)));}},[cameraActive]);
 useEffect(()=>()=>{cameraTicket.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;},[]);
 function stopCamera(){cameraTicket.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCameraActive(false);observation.current.pose=null;if(video.current)video.current.srcObject=null;}
 async function startCamera(){stopCamera();const ticket=cameraTicket.current;try{const next=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:'user'},audio:false});if(ticket!==cameraTicket.current){next.getTracks().forEach(t=>t.stop());return;}stream.current=next;setFile(null);setKind('camera');setCameraActive(true);setTracking(true);setSettings(s=>({...s,pitch:0,yaw:0}));setError('');}catch(e){setError(`摄像头无法开启：${e instanceof Error?e.message:String(e)}`);}}
 function update<K extends keyof CastSettings>(key:K,value:CastSettings[K]){setSettings(s=>({...s,[key]:value}));}
 async function loadSvg(file:File){try{if(file.size>20_000_000)throw new Error('SVG 超过 20 MB');const text=await file.text();castingAsset(text);onAsset({text,name:file.name});setError('');}catch(e){setError(String(e));}}
 function loadMedia(file:File){if(!file.type.startsWith('image/')&&!file.type.startsWith('video/')){setError('请选择浏览器支持的图片或视频。');return;}stopCamera();setKind(file.type.startsWith('video/')?'video':'photo');setFile(file);setError('');setTracking(true);setSettings(s=>({...s,pitch:0,yaw:0}));session.videoTime=0;session.time=0;elapsed.current=0;clock.current=0;}
 async function exportPng(){if(!engine.current||!source.value||exportLock.current)return;exportLock.current=true;setExporting(true);setPlaying(false);video.current?.pause();const renderer=engine.current,originalSize=renderer.renderer.getSize(new Vector2()),originalRatio=renderer.renderer.getPixelRatio();try{
  const scale=Math.min(1,4096/Math.max(dimensions.w,dimensions.h)),canvas=document.createElement('canvas');canvas.width=Math.round(dimensions.w*scale);canvas.height=Math.round(dimensions.h*scale);
  const ctx=canvas.getContext('2d')!;if(mirror){ctx.translate(canvas.width,0);ctx.scale(-1,1);}
  const media=kind==='photo'?photo.current:video.current;if(media)ctx.drawImage(media,0,0,canvas.width,canvas.height);else{ctx.fillStyle='#091313';ctx.fillRect(0,0,canvas.width,canvas.height);}
  await renderer.textures(source.value.duration?clock.current%source.value.duration:0,Math.min(2048,Math.max(512,Math.floor(Math.sqrt(16_000_000/source.value.layers.length)))));
  if(engine.current!==renderer)return;
  renderer.renderer.setPixelRatio(1);renderer.renderer.setSize(canvas.width,canvas.height,false);renderer.draw(state.current.settings,lastPose.current,elapsed.current,visibility.current,0);ctx.drawImage(renderer.renderer.domElement,0,0,canvas.width,canvas.height);
  const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('无法编码 PNG');const link=document.createElement('a'),u=URL.createObjectURL(blob);link.href=u;link.download='casting-'+(asset?.name.replace(/\.[^.]+$/,'')||'sigil')+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(u),1000);
 }catch(e){setError(`导出失败：${e}`);}finally{if(engine.current===renderer){renderer.renderer.setPixelRatio(originalRatio);renderer.renderer.setSize(originalSize.x,originalSize.y,false);}exportLock.current=false;setExporting(false);}}
 const slider=(key:keyof CastSettings,label:string,min:number,max:number,step:number)=><label className="cast-field">{label}<output>{Number(settings[key]).toFixed(step<1?2:0)}</output><input aria-label={label} type="range" min={min} max={max} step={step} value={Number(settings[key])} onChange={e=>update(key,Number(e.target.value) as never)}/></label>;
 return <main className="cast-page" onDrop={e=>{e.preventDefault();e.stopPropagation();const f=e.dataTransfer.files[0];if(f){if(f.name.endsWith('.svg'))void loadSvg(f);else loadMedia(f);}}}>
  <section className="intro"><div><div className="eyebrow">PALM / PROJECTION / MANIFESTATION</div><h1>让术式，在掌前展开。</h1><p>{asset?asset.name:'选择法阵，然后让光从掌心生长。'}</p></div><button disabled={!source.value||exporting} onClick={()=>void exportPng()}>{exporting?'正在合成…':'导出当前画面 PNG ↓'}</button></section>
  <div className="cast-workspace"><section className="cast-preview"><div className="cast-stage" style={{aspectRatio:`${dimensions.w}/${dimensions.h}`,transform:mirror?'scaleX(-1)':undefined}} onPointerDown={e=>{const rect=e.currentTarget.getBoundingClientRect();if(kind==='video'&&e.clientY>rect.bottom-45)return;setTracking(false);setAnchor(a=>({...a,x:mirror?1-(e.clientX-rect.left)/rect.width:(e.clientX-rect.left)/rect.width,y:(e.clientY-rect.top)/rect.height}));}}>
   {(url||cameraActive)&&(kind==='photo'?<img ref={photo} src={url} alt="施法背景" onLoad={e=>setDimensions({w:e.currentTarget.naturalWidth,h:e.currentTarget.naturalHeight})} onError={()=>setError('图片无法解码，请换用 PNG 或 JPEG。')}/>:<video ref={video} src={cameraActive?undefined:url} muted={cameraActive} controls={!cameraActive} playsInline onPlay={()=>setPlaying(true)} onPause={()=>{if(kind==='video')setPlaying(false);}} onSeeking={()=>{tracker.current?.reset();lastVideoFrame.current=-1;observation.current.pose=null;gesture.current.reset();seekReveal.current=true;}} onLoadedMetadata={e=>{setDimensions({w:e.currentTarget.videoWidth,h:e.currentTarget.videoHeight});if(!cameraActive){e.currentTarget.currentTime=session.videoTime||0;setPlaying(false);}}} onError={()=>setError('视频无法解码，请换用 MP4 / H.264 或 WebM。')}/>)}
   {debug&&<svg className="hand-debug" viewBox={`0 0 ${dimensions.w} ${dimensions.h}`}>{observation.current.hands.flatMap((h,j)=>h.landmarks.map((p,i)=><circle key={`${j}-${i}`} cx={p.x*dimensions.w} cy={p.y*dimensions.h} r={dimensions.w*.003} fill={j?'#ffd27b':'#7effdf'}/>))}</svg>}
   <div ref={host} className="cast-canvas"/>{!url&&<span className="cast-watermark">空间预览 · 点击画面放置掌心锚点</span>}
  </div><div className="transport"><button onClick={()=>{setPlaying(p=>!p);if(kind==='video'&&video.current){if(video.current.paused)void video.current.play().catch(e=>setError(String(e)));else video.current.pause();}}}>{playing?'Ⅱ 暂停法阵':'▷ 播放法阵'}</button><button onClick={()=>{elapsed.current=0;gesture.current.elapsed=0;setPlaying(true);}}>重新展开</button><input aria-label="法阵时间" type="range" min="0" max={source.value?.duration||1} step=".01" value={time} onChange={e=>{clock.current=+e.target.value;setTime(+e.target.value);setPlaying(false);if(kind==='video'&&video.current){video.current.pause();video.current.currentTime=+e.target.value;}}}/><output>{time.toFixed(1)}s</output></div><p className="cast-hint">{source.value?.single?'该 SVG 缺少独立层信息，按单层素材显示。':`${source.value?.layers.length||0} 个空间图层 · 副环保留在所属主层`}</p><p className="cast-hint" role="status">{tracking?status:'手动模式 · 点击图片放置法阵'}</p></section>
  <aside className="cast-controls"><div className="view-tabs">{[['input','输入与素材'],['space','空间与透视'],['output','展开与输出']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
   {tab==='input'&&<div className="cast-control-body"><span className="eyebrow">01 / SOURCE</span><button onClick={()=>cameraActive?stopCamera():void startCamera()}>{cameraActive?'关闭摄像头':'开启摄像头'}</button><label className="file-button">选择照片或视频<input aria-label="施法媒体文件" type="file" accept="image/*,video/*" onChange={e=>{const f=e.target.files?.[0];if(f)loadMedia(f);e.target.value='';}}/></label><p>{file?.name||'可先使用空白舞台调整法阵。'}</p><label><input type="checkbox" checked={tracking} onChange={e=>{setTracking(e.target.checked);if(e.target.checked)setSettings(s=>({...s,pitch:0,yaw:0}));}}/>自动跟随张开的手掌</label><label>施法手<select aria-label="施法手" value={handChoice} onChange={e=>setHandChoice(e.target.value)}><option value="auto">自动锁定</option><option value="Left">左手</option><option value="Right">右手</option></select></label><label><input type="checkbox" checked={debug} onChange={e=>setDebug(e.target.checked)}/>显示手部关键点</label><hr/><span className="eyebrow">02 / SIGIL</span><button onClick={onCurrent}>使用当前代码法阵</button><button onClick={onImported}>使用已导入法阵</button><label className="file-button">导入施法 SVG<input aria-label="施法 SVG 文件" type="file" accept=".svg" onChange={e=>{const f=e.target.files?.[0];if(f)void loadSvg(f);e.target.value='';}}/></label></div>}
   {tab==='space'&&<div className="cast-control-body">{slider('size','法阵半径（掌宽）',.3,6,.1)}{slider('offset','离掌距离',0,3,.05)}{slider('spacing','图层间距',0,3,.05)}{slider('fov','相机视场角',25,100,1)}{slider('pitch','俯仰校正',-85,85,1)}{slider('yaw','偏航校正',-85,85,1)}{slider('roll','平面旋转',-180,180,1)}<label className="cast-field">掌心深度<output>{anchor.depth.toFixed(1)}</output><input aria-label="掌心深度" type="range" min="3" max="25" step=".1" value={anchor.depth} onChange={e=>setAnchor(a=>({...a,depth:+e.target.value}))}/></label><label><input type="checkbox" checked={settings.flip} onChange={e=>update('flip',e.target.checked)}/>翻转施法方向</label><label><input type="checkbox" checked={settings.reverse} onChange={e=>update('reverse',e.target.checked)}/>反转图层顺序</label><label>查看图层<select aria-label="施法图层" value={settings.solo} onChange={e=>update('solo',+e.target.value)}><option value="-1">所有图层</option>{source.value?.layers.map((l,i)=><option key={l.id} value={i}>{l.name}</option>)}</select></label></div>}
   {tab==='output'&&<div className="cast-control-body">{slider('duration','术式展开时长（秒）',.4,5,.1)}{slider('glow','光线强度',0,1,.05)}<label className="cast-field">法阵不透明度<output>{Math.round(settings.opacity*100)}%</output><input aria-label="法阵不透明度" type="range" min="0" max="200" step="5" value={Math.round(settings.opacity*100)} onChange={e=>update('opacity',Number(e.target.value)/100)}/></label><p>100% 保持原始透明度；超过 100% 增强半透明线条的遮盖力度，空白仍透明。光线强度只调亮度。</p><label><input type="checkbox" checked={mirror} onChange={e=>setMirror(e.target.checked)}/>镜像画面与法阵</label><p>术式由小到大逐层展开，旋转和表针继续按原有轨迹运行。点击「重新展开」可再次观看。</p><p>导出当前画面，长边最多 4096 像素。普通单目输入使用相对掌宽定位。</p></div>}
   {tab==='space'&&source.value&&<div className="cast-control-body"><span className="eyebrow">沿施法方向 / 层序</span>{settings.order.map((i,rank)=><div className="cast-order" key={i}><span>{rank+1}. {source.value?.layers[i]?.name}</span>{[-1,1].map(d=><button key={d} aria-label={`${d<0?'前移':'后移'}图层 ${rank+1}`} disabled={rank+d<0||rank+d>=settings.order.length} onClick={()=>setSettings(s=>{const order=[...s.order];[order[rank],order[rank+d]]=[order[rank+d],order[rank]];return {...s,order};})}>{d<0?'↑':'↓'}</button>)}</div>)}<svg aria-label="层距侧视示意" viewBox="0 0 280 90"><path d="M12 45H268l-8 -5m8 5l-8 5" fill="none" stroke="#537768"/><text x="6" y="82" fill="#8caa9c" fontSize="10">掌心 → 施法方向（相对距离）</text>{settings.order.map((i,rank)=><g key={i} transform={`translate(${30+(settings.offset+rank*settings.spacing)*220/Math.max(3,settings.offset+(settings.order.length-1)*settings.spacing)} 45)`}><path d="M0 -28V28" stroke={rank%2?'#dab978':'#81d7c1'}/><text x="4" y="-20" fill="#a5b9a9" fontSize="10">{rank+1}</text></g>)}</svg><p>正面对准施法轴时各层可能重叠；转动掌面或增加层距可观察空间深度。</p></div>}
  </aside></div>{(error||source.error)&&<p className="error" role="alert">{error||source.error}</p>}
 </main>;
}
