import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {analyzeCSource,type Model,type Node} from './analysis';
import {Scene} from './SceneV3';
import {buildPlanes,mainRadii,radialPeriod,orbitalPeriod,CORE_PERIOD,inferResultKind,resultSeals,type ResultKind,type ViewMode} from './planes';
import {sigils} from './sigils';
import {Editor} from './Editor';
import {samples} from './sample';
import {buildTimeline,samplePlayback} from './playback';
import './style.css';
function App(){
 const [source,setSource]=useState(samples['dijkstra.c']),[filename,setFilename]=useState('dijkstra.c');
 const [mode,setMode]=useState<ViewMode>('stack'),[hidden,setHidden]=useState<string[]>([]),[solo,setSolo]=useState<string|null>(null),[spacing,setSpacing]=useState(160),[orbit,setOrbit]=useState(18);
 const [resultChoice,setResultChoice]=useState<ResultKind|'auto'>('auto');
 useEffect(()=>{setHidden([]);setSolo(null);setResultChoice('auto');},[source]);
 const [model,setModel]=useState<Model|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true);
 const [selected,setSelected]=useState<Node|null>(null),[hover,setHover]=useState<Node|null>(null),[expanded,setExpanded]=useState<string|null>(null);
 const [playing,setPlaying]=useState(false),[time,setTime]=useState(0),[speed,setSpeed]=useState(1),[tilt,setTilt]=useState(.57),[zoom,setZoom]=useState(1),[glow,setGlow]=useState(true);
 const svgRef=useRef<SVGSVGElement>(null),fileRef=useRef<HTMLInputElement>(null),version=useRef(0);
 useEffect(()=>{const ticket=++version.current;setBusy(true);setPlaying(false);const id=setTimeout(()=>{analyzeCSource(source).then(m=>{if(ticket!==version.current)return;setModel(m);setError('');setSelected(null);setExpanded(null);setTime(0);setBusy(false);}).catch(e=>{if(ticket===version.current){setError(String(e));setBusy(false);}});},300);return()=>clearTimeout(id);},[source]);
 const timeline=useMemo(()=>buildTimeline(model||{functions:[],trace:[],sourceHash:'',semanticHash:'',diagnostics:[],directives:[]}),[model]);
 const playback=samplePlayback(timeline,time),step=playback.step;
 const seek=(index:number)=>{setPlaying(false);setTime(timeline.events[index]?.start||0);};
 useEffect(()=>{if(!playing)return;let frame=0,last=0;const loop=(now:number)=>{if(last)setTime(t=>Math.min(timeline.duration,t+Math.min(.08,(now-last)/1000)*speed));last=now;frame=requestAnimationFrame(loop);};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame);},[playing,speed,timeline]);
 useEffect(()=>{if(playing&&time>=timeline.duration)setPlaying(false);},[time,playing,timeline.duration]);
 async function loadFile(file:File){if(!file.name.toLowerCase().endsWith('.c')){setError('请选择 .c 文件。');return;}if(file.size>2_000_000){setError('文件超过 2 MB，请选择较小的 C 文件。');return;}try{const s=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());setFilename(file.name);setSource(s);}catch{setError('无法按 UTF-8 读取文件，请先将文件保存为 UTF-8。');}}
 function download(blob:Blob,ext:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename.replace(/\.c$/i,'')+'-sigil.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function exportImage(png:boolean){try{if(!svgRef.current)return;const clone=svgRef.current.cloneNode(true) as SVGSVGElement;clone.setAttribute('width','1680');clone.setAttribute('height','1460');clone.removeAttribute('style');clone.setAttribute('aria-label',`Code to Magic ${model?.sourceHash}`);const blob=new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml;charset=utf-8'});if(!png){download(blob,'svg');return;}const url=URL.createObjectURL(blob);try{const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');c.width=1680;c.height=1460;c.getContext('2d')!.drawImage(img,0,0);const out=await new Promise<Blob|null>(resolve=>c.toBlob(resolve,'image/png'));if(out)download(out,'png');}finally{URL.revokeObjectURL(url);}}catch(e){setError(`导出失败：${String(e)}`);}}
 const planes=model?buildPlanes(model):[];
 const radiusReport=mainRadii(planes);
 const resultKind=resultChoice==='auto'?(model?inferResultKind(model):'unknown'):resultChoice;
 const info=hover||selected; const active=model?.functions.flatMap(f=>f.nodes).find(n=>n.id===playback.event?.nodeId);
 return <div className="app" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)void loadFile(f);}}>
  <header><a className="brand" href="#"><span className="brand-seal">✳</span><span>CODE TO MAGIC<small>代码炼成术 / LOCAL ATELIER</small></span></a><div className="header-right"><span className="local"><i/> 本地解析 · 文件不会上传</span><span className="edition">EXPERIMENT 001</span></div></header>
  <main><section className="intro"><div><div className="eyebrow">THE ANATOMY OF A SPELL</div><h1>让逻辑，显现为魔法。</h1><p>每一个函数是一重法环，每一道分支是一枚符文。</p></div><div className="intro-note">C SOURCE → ARCANE GEOMETRY<br/><span>结构赋予形态，指纹留下印记。</span></div></section>
  <div className="workspace"><section className="code-panel"><div className="panel-title"><span><b>01</b> 源典 SOURCE</span><button onClick={()=>fileRef.current?.click()}>导入 .c ↗</button><input ref={fileRef} type="file" accept=".c" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void loadFile(f);e.target.value='';}}/></div><div className="filebar"><span>◇ {filename}</span><select aria-label="示例代码" value={samples[filename]===source?filename:''} onChange={e=>{if(e.target.value){setFilename(e.target.value);setSource(samples[e.target.value]);}}}><option value="" disabled>选择示例</option>{Object.keys(samples).map(k=><option key={k}>{k}</option>)}</select></div>
  <Editor source={source} onChange={setSource} selection={selected?.range||null} onPosition={p=>{const ns=model?.functions.flatMap(f=>f.nodes).filter(n=>n.range.start<=p&&n.range.end>=p).sort((a,b)=>(a.range.end-a.range.start)-(b.range.end-b.range.start));setSelected(ns?.[0]||null);}}/>
  <div className="code-footer"><span>{source.split('\n').length} LINES</span><span>UTF-8 / C</span><span>{busy?'解析中…':model?.diagnostics.length?`${model.diagnostics.length} 处待检查`:'● 已同步'}</span></div></section>
  <section className="visual-panel"><div className="panel-title"><span><b>02</b> 法阵 MANIFESTATION</span><div className="export"><button disabled={!model||busy} onClick={()=>void exportImage(false)}>↓ SVG</button><button disabled={!model||busy} onClick={()=>void exportImage(true)}>↓ PNG</button></div></div>
  <div className="view-tabs">{(['stack','front','single'] as ViewMode[]).map(v=><button key={v} aria-pressed={mode===v} onClick={()=>setMode(v)}>{({stack:'立体叠层',front:'正视重叠',single:'单层蓝本'})[v]}</button>)}<label>层距<input aria-label="层间距离" type="range" min="0" max="420" value={spacing} disabled={mode!=='stack'} onChange={e=>setSpacing(+e.target.value)}/><output>{spacing}</output></label><label>公转<input aria-label="副环公转周期" type="range" min="7" max="25" value={orbit} onChange={e=>setOrbit(+e.target.value)}/><output>{orbit}s</output></label></div>
  <div className="scene-wrap"><div className="scene-label"><span>CONCENTRIC FIELD</span><small>平面符文投影 · 旋转周期以 1× 为准</small></div>{model?<Scene model={model} timeline={timeline} time={time} step={step} selected={selected?.id||null} onSelect={setSelected} onHover={setHover} expanded={expanded} setExpanded={setExpanded} tilt={tilt} zoom={zoom} glow={glow} svgRef={svgRef} mode={mode} hidden={hidden} solo={solo} spacing={spacing} orbit={orbit} resultKind={resultKind}/>:<div className="loading">正在构建符文语言…</div>}<div className="scene-tools"><button title="缩小" aria-label="缩小" onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>−</button><button title="还原视图" onClick={()=>{setZoom(1);setTilt(.57);}}>⊙</button><button title="放大" aria-label="放大" onClick={()=>setZoom(z=>Math.min(1.7,z+.1))}>＋</button></div></div>
  <div className="layer-panel" aria-label="图层面板">{planes.map((l,i)=><div className="layer-row" key={l.id} style={{borderLeftColor:l.color}}><label><input aria-label={`显示图层 ${l.name}`} type="checkbox" disabled={mode==='single'} checked={!hidden.includes(l.id)} onChange={e=>setHidden(h=>e.target.checked?h.filter(id=>id!==l.id):[...h,l.id])}/><span style={{color:l.color}}>{String(i+1).padStart(2,'0')} · {l.name}</span></label><small>{l.functions.map((f,j)=>`${f.name==='main'?'中环':f.name} R${radiusReport.get(f.id)} · ${radialPeriod(l.period,j)}s`).join(' / ')}{l.satellites.map((s,j)=>` / 副环 ${s.fn.name} 自转 ${radialPeriod(l.period,j+1)}s / 公转 ${orbitalPeriod(orbit,i+j)}s`)} · 结果印 {CORE_PERIOD}s</small><button aria-pressed={mode==='single'&&(solo||planes[0]?.id)===l.id} onClick={()=>{setSolo(l.id);setMode('single');}}>单独查看</button></div>)}</div>
  <div className="transport"><button className="play" disabled={!timeline.events.length||busy} onClick={()=>{if(time>=timeline.duration)setTime(0);setPlaying(p=>!p);}}>{playing?'Ⅱ 暂停':'▷ 演示'}</button><button aria-label="下一步" disabled={!timeline.events.length} onClick={()=>seek((step+1)%Math.max(1,timeline.events.length))}>步进 →</button><input aria-label="演示进度" type="range" min="0" max={Math.max(0,timeline.events.length-1)} value={step} onChange={e=>seek(+e.target.value)}/><span className="counter">{String(step+1).padStart(2,'0')} / {timeline.events.length}</span><select aria-label="演示速度" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[.5,1,2].map(n=><option key={n} value={n}>{n}×</option>)}</select></div>
 </section></div>
 <section className="underbar"><div className="readout"><span className="eyebrow">符文释义 / INSPECT</span><strong>{info?info.label:active?active.label:'选择法阵中的符文'}</strong><small>{info?`第 ${info.range.line}–${info.range.endLine} 行 · ${info.family} · 点击符文定位源代码`:'悬停查看含义 · 点击双向定位 · 动画不代表真实运行'}</small></div><div className="settings"><label>中环结果<select aria-label="最终结果类型" value={resultChoice} onChange={e=>setResultChoice(e.target.value as ResultKind|'auto')}><option value="auto">自动：{resultSeals[resultKind].label}（启发式）</option>{Object.entries(resultSeals).map(([k,s])=><option key={k} value={k}>{s.label}</option>)}</select></label><label>视角<input aria-label="透视倾角" type="range" min=".25" max="1" step=".01" value={tilt} onChange={e=>setTilt(+e.target.value)}/></label><label><input type="checkbox" checked={glow} onChange={e=>setGlow(e.target.checked)}/>辉光</label>{expanded&&<button onClick={()=>setExpanded(null)}>折叠语句</button>}</div></section>
 {error&&<div role="alert" className="error">{error}</div>}
 {!!model?.diagnostics.length&&<div className="error" role="status">部分语法尚不完整：{model.diagnostics.slice(0,8).map((d,i)=><button key={i} onClick={()=>setSelected({id:'error',kind:'ERROR',label:'语法错误',range:d,depth:0,family:'general',pointers:0})}>第 {d.line} 行</button>)}。法阵保留可解析部分。</div>}
 <footer><div className="legend">{planes.map(l=><span key={l.id}><i style={{background:l.color}}/>{l.name}</span>)}</div><span>{planes.length} 图层 · {model?.functions.length||0} 函数环</span><small>INSPIRED BY MYSTICAL · ORIGINAL GLYPHS</small></footer>
 <details><summary>如何阅读这张法阵</summary><p>每层来自同一平面蓝本，立体视图将整层一起倾斜与平移，正视图消除层距。不同颜色代表不同图层。简单函数（不超过 12 个结构节点、无分支循环与内部调用）共面并用半径区分，小型单调用者叶函数改为调用者的副环，递归与共享函数仍独立。主环使用实际 SVG 符文宽度、可读字距、徽章与副环占用约束自动求紧凑半径（R），长表达式按实际符文宽度分配圆弧。层距可在 0–420 间自由调整，允许投影交叠；画布自动适配层间高度。内层重要节点按邻近节点与边界空白自适应放大。主副环周期分布在 3–20 秒，同层主副环周期差不超过 5 秒；副环独立公转为 7–25 秒，中心以函数结果类型印替代名称（静态启发式），名称保留在悬停和图层面板。中心结果印例外，只保留中环（main）的中心结果印，其他同心主环省略中心，副环保留各自结果印，周期为 12 秒；速度倍率会同比改变实际周期。点击“演示”启动指针，函数环持续自转，调用挂起时表针锁定当前符文并随环旋转；暂停冻结当前帧，SVG / PNG 导出当前视图。</p><p>线条符文由 C 关键字及运算符组合：分叉代表条件、回环代表循环、收束代表返回。选中调用节点时显示调用虚线，闭环表示递归。条件使用菱形，计数循环用方形，条件循环用透镜形，后置循环用三角，选择结构用六边形。每个独立环的外轮廓依据自身结果类型：路径为六瓣冠、数值为齿轮、文本为双叶框、集合为蜂巢、判定为四向冠，未分类为八瓣环。同类型共享视觉语法；中环下拉选项只改变中环，不改变其他函数。结果类型自动判别仅依据函数名、返回类型与 API 特征，不是运行推断，可以手动覆盖。演示为静态结构遍历，不执行 C 代码；中环短时针、分层函数中分针和副环短秒针全部常驻，三者采用相同运行规则。未调用时保留初始位置，返回后停在最后一个符文并随环旋转。指针平滑指向当前语句，调用者停在调用位置等待返回，速度跟随演示倍率；外部调用和递归回路短暂停留。分支展示所有替代路径，循环只展开一次。宏不会展开，函数指针调用不解析目标。</p><div className="sigil-catalog">{Object.entries(sigils).slice(0,44).map(([k,s])=><div key={k}><svg viewBox="-20 -20 40 40"><path d={s.path} fill="none" stroke="currentColor" strokeWidth="1.2"/></svg><span>{k}<small>{s.meaning}</small></span></div>)}</div><p>微观刻度来自 UTF-8 文件内容的 SHA-256；图像不是无损代码编码，完整指纹可用于核对。</p><code>{model?.sourceHash}</code>{!!model?.directives.length&&<p>预处理指令：{model.directives.join(' · ')}</p>}</details>
 </main></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
